version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "monthly"
  ignore:
  - dependency-name: "coverage"
  - dependency-name: "black"
  groups:
    python-packages:
      patterns:
      - "*"
